// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GnmiJuniperTelemetryHeader.proto

/*
Package GnmiJuniperTelemetryHeader is a generated protocol buffer package.

It is generated from these files:
	GnmiJuniperTelemetryHeader.proto

It has these top-level messages:
	GnmiJuniperTelemetryHeader
*/
package GnmiJuniperTelemetryHeader

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Present as first gNMI update in all packets
type GnmiJuniperTelemetryHeader struct {
	// router name:export IP address
	SystemId string `protobuf:"bytes,1,opt,name=system_id,json=systemId" json:"system_id,omitempty"`
	// line card / RE (slot number)
	ComponentId uint32 `protobuf:"varint,2,opt,name=component_id,json=componentId" json:"component_id,omitempty"`
	// PFE (if applicable)
	SubComponentId uint32 `protobuf:"varint,3,opt,name=sub_component_id,json=subComponentId" json:"sub_component_id,omitempty"`
	// Path contains useful information on identiying which sensor,
	// resoruce string and producer the data corresponds to.
	// "internal_sensor_name:internal_path:external_path:component"
	// e.g.:
	// "sensor_1006:/junos/system/linecard/cpu/memory/:/junos/system/linecard/cpu/memory/:PFE"
	Path string `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	// Sequence number, monotonically increasing for each
	// system_id, component_id, sub_component_id + path.
	SequenceNumber uint64 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
}

func (m *GnmiJuniperTelemetryHeader) Reset()                    { *m = GnmiJuniperTelemetryHeader{} }
func (m *GnmiJuniperTelemetryHeader) String() string            { return proto.CompactTextString(m) }
func (*GnmiJuniperTelemetryHeader) ProtoMessage()               {}
func (*GnmiJuniperTelemetryHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GnmiJuniperTelemetryHeader) GetSystemId() string {
	if m != nil {
		return m.SystemId
	}
	return ""
}

func (m *GnmiJuniperTelemetryHeader) GetComponentId() uint32 {
	if m != nil {
		return m.ComponentId
	}
	return 0
}

func (m *GnmiJuniperTelemetryHeader) GetSubComponentId() uint32 {
	if m != nil {
		return m.SubComponentId
	}
	return 0
}

func (m *GnmiJuniperTelemetryHeader) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GnmiJuniperTelemetryHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*GnmiJuniperTelemetryHeader)(nil), "GnmiJuniperTelemetryHeader")
}

func init() { proto.RegisterFile("GnmiJuniperTelemetryHeader.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x70, 0xcf, 0xcb, 0xcd,
	0xf4, 0x2a, 0xcd, 0xcb, 0x2c, 0x48, 0x2d, 0x0a, 0x49, 0xcd, 0x49, 0xcd, 0x4d, 0x2d, 0x29, 0xaa,
	0xf4, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x3a, 0xcc, 0xc8,
	0x25, 0x85, 0x5b, 0x91, 0x90, 0x34, 0x17, 0x67, 0x71, 0x65, 0x71, 0x49, 0x6a, 0x6e, 0x7c, 0x66,
	0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x07, 0x44, 0xc0, 0x33, 0x45, 0x48, 0x91, 0x8b,
	0x27, 0x39, 0x3f, 0xb7, 0x20, 0x3f, 0x2f, 0x35, 0xaf, 0x04, 0x24, 0xcf, 0xa4, 0xc0, 0xa8, 0xc1,
	0x1b, 0xc4, 0x0d, 0x17, 0xf3, 0x4c, 0x11, 0xd2, 0xe0, 0x12, 0x28, 0x2e, 0x4d, 0x8a, 0x47, 0x51,
	0xc6, 0x0c, 0x56, 0xc6, 0x57, 0x5c, 0x9a, 0xe4, 0x8c, 0xa4, 0x52, 0x88, 0x8b, 0xa5, 0x20, 0xb1,
	0x24, 0x43, 0x82, 0x05, 0x6c, 0x09, 0x98, 0x2d, 0xa4, 0xce, 0xc5, 0x5f, 0x9c, 0x5a, 0x58, 0x9a,
	0x9a, 0x97, 0x9c, 0x1a, 0x9f, 0x57, 0x9a, 0x9b, 0x94, 0x5a, 0x24, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1,
	0x12, 0xc4, 0x07, 0x13, 0xf6, 0x03, 0x8b, 0x26, 0xb1, 0x81, 0x3d, 0x63, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x37, 0xca, 0x24, 0x58, 0xf0, 0x00, 0x00, 0x00,
}
